# Generated by Django 5.0.6 on 2024-05-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('registered_on', models.DateField()),
                ('account_type', models.CharField(choices=[(0, "Boshlang'ich "), (1, "Qo'shimcha ")], default=0, max_length=1)),
            ],
        ),
    ]
