# Generated by Django 5.0.6 on 2024-06-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Independent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('E', "Boshlang'ich "), ('A', "Qo'shimcha ")], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Practical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('E', "Boshlang'ich "), ('A', "Qo'shimcha ")], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('E', "Boshlang'ich "), ('A', "Qo'shimcha ")], default='E', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos_uploaded')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('account_type', models.CharField(choices=[('E', "Boshlang'ich "), ('A', "Qo'shimcha ")], default='E', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='account_type',
            field=models.CharField(choices=[('E', "Boshlang'ich "), ('A', "Qo'shimcha ")], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='registered_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
